apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: frameworks.maestro.k8s.io
spec:
  group: maestro.k8s.io
  names:
    kind: Framework
    plural: frameworks
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            serviceSpec:
              properties:
                name:
                  type: string
                plans:
                  type: object
                pods:
                  type: object
                scheduler:
                  properties:
                    principal:
                      type: string
                    user:
                      type: string
                    zookeeper:
                      type: string
                  required:
                  - principal
                  - zookeeper
                  - user
                  type: object
              required:
              - name
              - scheduler
              - pods
              - plans
              type: object
          required:
          - serviceSpec
          type: object
        status:
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
